FROM node:8.7-alpine

RUN apk update && apk add git
RUN npm install aurelia-cli -g

RUN npm install aurelia-bootstrap -s \
    npm install velocity-animate -s \
    npm install tether -s


EXPOSE 9000
EXPOSE 3001
