version: "3"
services:

  server:
    build: ./src/server
    volumes:
      - "./src/server:/go/src/app"
      - "./animations:/animations"
    ports:
      - "3000:3000"
      - "7890:7890"
      - "7899:7899"
      - "8080:8080"
    command: /bin/sh -c "go run *.go"
    environment:
      - DISPLAY=:1

  aurelia:
    build: ./src/server/static/siknas-skylt
    volumes:
      - "./src/server/static/siknas-skylt:/shared"
    working_dir: /shared
    command: /bin/sh -c "yarn --no-bin-links && aurelia build --watch"

